name: raspberrypi-4-unit-tests
on: [push]
jobs:
  build:
    runs-on: raspberrypi-4
    steps:
      - uses: actions/checkout@v2
      - name: configure & build
        run: |
          cd lib && ./configure --enable-neon && cd ..
          make -j 4 -C lib
          make -j 4 -C bin
          make -j 4 -C test
      - name: tests
        run: |
          make -C test test
